version: '3.7'
services:
  app:
    container_name: hello
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    tty: true
    ports:
      - "8085:3000"
    links:
      - "mongo:dbmongo"
      # this feature is no longer need except for aliases
    environment:
      # - "NODE_ENV=docker"
      - "admin-panel_jwt=123456"
      - "adminPanel_jwt=123456"
      - "PORT=3000"
    depends_on: ["mongo"]
  mongo:
    restart: always
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
  mysql:
    image: mysql:latest
    container_name: dev_mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_schema

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80
volumes:
  mongo-data: